services: 
  find-a-friend-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=igorx
      - POSTGRESQL_PASSWORD=pass@123
      - POSTGRESQL_DATABASE=find-a-friend
      - POSTGRESQL_REPLICATION_USE_PASSFILE=no